### model
model_name_or_path: /data2/dmz/multi_Inference_model/R1-Onevision/R1-Onevision-7B
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: cocoun
do_train: true
finetuning_type: lora
quantization_bit: 4
lora_rank: 12
lora_target: all

### dataset joebiden_final dataGA66_trump_new
dataset: dataGA66_trump_new
template: qwen2_vl
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/r1-onevision-7b-lora-sft-dataGA66-joebiden_final-cocoun-33epochs
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 0.00005
num_train_epochs: 70
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
report_to: none
### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 100
